# .streamlit/secrets.toml
TEXT_PREPROC_URL = "https://www.dropbox.com/scl/fi/zpftggop63g87uiev9nzt/text_preproc.joblib?rlkey=ogzkino3681ttoa26fc04a282&dl=1"
FINAL_ESTIMATOR_URL = "https://www.dropbox.com/scl/fi/kdmd7njht3anvctd2zjbv/final_estimator.joblib?rlkey=vks5rl4cxrnvlbsojkmvcezwm&dl=1"